In [1]:
import pandas as pd

In [20]:
csv = pd.read_csv('edf_mix_2014.csv', delimiter=";", encoding = "ISO-8859-1")

/Users/lpregniard/.conda/envs/data_science/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3063: DtypeWarning: Columns (18,19,20,21,22) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [21]:
csv = csv.dropna()

In [22]:
csv['Date'] = pd.to_datetime(csv['Date'], dayfirst=True)

In [23]:
csv.set_index(csv["Date"],inplace=True)

In [24]:
csv

,Périmètre,Nature,Date,Heures,Consommation,Prévision J-1,Prévision J,Fioul,Charbon,Gaz,...,Gaz - TAC,Gaz - Cogén.,Gaz - CCG,Gaz - Autres,Hydraulique - Fil de l?eau + éclusée,Hydraulique - Lacs,Hydraulique - STEP turbinage,Bioénergies - Déchets,Bioénergies - Biomasse,Bioénergies - Biogaz
Date,,,,,,,,,,,,,,,,,,,,,
2014-01-01,France,Données définitives,2014-01-01,00:00,64660.0,63200.0,63200.0,454.0,-21.0,2303.0,...,-1.0,1809.0,422.0,72.0,5662.0,2125.0,693.0,460.0,165.0,179.0
2014-01-01,France,Données définitives,2014-01-01,00:30,63494.0,62100.0,61500.0,281.0,-6.0,2367.0,...,-1.0,1847.0,438.0,83.0,5569.0,2450.0,495.0,592.0,170.0,181.0
2014-01-01,France,Données définitives,2014-01-01,01:00,61362.0,59900.0,59900.0,281.0,-7.0,2188.0,...,-1.0,1848.0,258.0,83.0,5457.0,2040.0,76.0,591.0,173.0,181.0
2014-01-01,France,Données définitives,2014-01-01,01:30,61217.0,60600.0,60300.0,281.0,-7.0,2190.0,...,-1.0,1853.0,255.0,83.0,5286.0,1849.0,0.0,595.0,174.0,180.0
2014-01-01,France,Données définitives,2014-01-01,02:00,60748.0,59900.0,60200.0,281.0,-6.0,2187.0,...,-1.0,1853.0,252.0,83.0,5201.0,1592.0,0.0,597.0,174.0,180.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2014-12-31,France,Données définitives,2014-12-31,21:30,69522.0,68100.0,68700.0,268.0,2220.0,3646.0,...,3.0,2135.0,1441.0,66.0,5144.0,1362.0,719.0,552.0,188.0,200.0
2014-12-31,France,Données définitives,2014-12-31,22:00,68850.0,67300.0,67900.0,272.0,2173.0,3615.0,...,3.0,2095.0,1450.0,66.0,5134.0,1319.0,473.0,555.0,182.0,200.0
2014-12-31,France,Données définitives,2014-12-31,22:30,70183.0,69300.0,70000.0,269.0,2344.0,3749.0,...,3.0,2097.0,1582.0,66.0,4930.0,1602.0,722.0,554.0,180.0,200.0
2014-12-31,France,Données définitives,2014-12-31,23:00,73714.0,72300.0,73000.0,268.0,2449.0,3752.0,...,3.0,2087.0,1595.0,66.0,4950.0,3246.0,2379.0,557.0,182.0,200.0
2014-12-31,France,Données définitives,2014-12-31,23:30,73617.0,72200.0,72800.0,268.0,2404.0,3574.0,...,3.0,2069.0,1435.0,66.0,4860.0,2337.0,1032.0,559.0,188.0,200.0

In [25]:
csv.shape

(17519, 36)

In [26]:
csv.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 17519 entries, 2014-01-01 to 2014-12-31
Data columns (total 36 columns):
Périmètre                               17519 non-null object
Nature                                  17519 non-null object
Date                                    17519 non-null datetime64[ns]
Heures                                  17519 non-null object
Consommation                            17519 non-null float64
Prévision J-1                           17519 non-null float64
Prévision J                             17519 non-null float64
Fioul                                   17519 non-null float64
Charbon                                 17519 non-null float64
Gaz                                     17519 non-null float64
Nucléaire                               17519 non-null float64
Eolien                                  17519 non-null float64
Solaire                                 17519 non-null float64
Hydraulique                             17519 non-null float64
Pompage                                 17519 non-null float64
Bioénergies                             17519 non-null float64
Ech. physiques                          17519 non-null float64
Taux de Co2                             17519 non-null float64
Ech. comm. Angleterre                   17519 non-null object
Ech. comm. Espagne                      17519 non-null object
Ech. comm. Italie                       17519 non-null object
Ech. comm. Suisse                       17519 non-null object
Ech. comm. Allemagne-Belgique           17519 non-null object
Fioul - TAC                             17519 non-null float64
Fioul - Cogén.                          17519 non-null float64
Fioul - Autres                          17519 non-null float64
Gaz - TAC                               17519 non-null float64
Gaz - Cogén.                            17519 non-null float64
Gaz - CCG                               17519 non-null float64
Gaz - Autres                            17519 non-null float64
Hydraulique - Fil de l?eau + éclusée    17519 non-null float64
Hydraulique - Lacs                      17519 non-null float64
Hydraulique - STEP turbinage            17519 non-null float64
Bioénergies - Déchets                   17519 non-null float64
Bioénergies - Biomasse                  17519 non-null float64
Bioénergies - Biogaz                    17519 non-null float64
dtypes: datetime64[ns](1), float64(27), object(8)
memory usage: 4.9+ MB

In [27]:
conso_by_day = csv["Consommation"].resample('D').sum()

In [28]:
conso_df = conso_by_day.to_frame()

In [29]:
conso_df["Date"] = conso_df.index

In [30]:
conso_df["Jour"] = conso_df["Date"].dt.day

In [31]:
conso_df["Mois"] = conso_df["Date"].dt.month

In [32]:
conso_df

            Consommation       Date  Jour  Mois
Date
2014-01-01     2732220.0 2014-01-01     1     1
2014-01-02     2907995.0 2014-01-02     2     1
2014-01-03     2955062.0 2014-01-03     3     1
2014-01-04     2809731.0 2014-01-04     4     1
2014-01-05     2794007.0 2014-01-05     5     1
...                  ...        ...   ...   ...
2014-12-27     3015918.0 2014-12-27    27    12
2014-12-28     3137894.0 2014-12-28    28    12
2014-12-29     3585153.0 2014-12-29    29    12
2014-12-30     3540884.0 2014-12-30    30    12
2014-12-31     3442193.0 2014-12-31    31    12

[365 rows x 4 columns]

In [33]:
conso_df.to_csv("conso_by_day_2014.csv")